### ISSUE TITLE
SQL query issue

### ISSUE THREAD

**Issue by briankabiro** [markchesire/ussd#1]
At the moment, I see that the query is using:  `admno = "100 "`

Have you tried changing it to `admno = $admno`

```sql
$sqlquery = "SELECT firstname, surname, marks, grade, position FROM performance WHERE admno = $admno;   
```

#### Another Possible issue
I also see that the database expects _admno_ to be an integer value. Maybe that could be the issue if this doesn't work.

**Comment by markchesire** [comment]
yeah have tried that initially but pulled blank result upon querying

**Comment by markchesire** [comment]
let see see the second option if it will fix it

**Comment by briankabiro** [comment]
Hey Mark. Any updates?

Were you able to get past it?
